"""Cross-venue market pairing.

Given markets from two venues, find pairs that are the same question and work
out which outcome on one corresponds to which on the other.

Two problems the naive approach gets wrong:

  * Cost. Comparing every market against every market is quadratic. With 300
    markets a side that is 90,000 similarity computations per venue pair per
    scan. Candidates are generated by inverted index on rare tokens first, so
    only plausible pairs are ever scored.

  * Precision. Titles that differ only in a number ("above $100k" vs "above
    $120k") score very high on string similarity and are completely different
    bets. Numbers and dates are compared exactly and a mismatch disqualifies
    the pair no matter how similar the prose.

Pairing is one-to-one and greedy by descending score: a market can appear in
at most one pair per venue combination.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from typing import Iterable, Optional

from matching import text as textlib
from models import Market, Outcome

# Tokens appearing in more than this share of a venue's markets carry no
# discriminating power and are not worth indexing on.
_COMMON_TOKEN_RATIO = 0.15


@dataclass
class PairCandidate:
    market_a: Market
    market_b: Market
    score: float
    notes: list[str] = field(default_factory=list)
    # (a_outcome, b_outcome) pairs that are complementary: buying both is the
    # hedge. Populated by `align_outcomes`.
    complements: list[tuple[Outcome, Outcome]] = field(default_factory=list)


def _index_by_token(markets: Iterable[Market]) -> dict[str, list[int]]:
    index: dict[str, list[int]] = defaultdict(list)
    materialised = list(markets)
    for position, market in enumerate(materialised):
        for token in textlib.tokens(market.title):
            index[token].append(position)

    ceiling = max(2, int(len(materialised) * _COMMON_TOKEN_RATIO))
    return {token: rows for token, rows in index.items() if len(rows) <= ceiling}


def _year_of(market: Market) -> Optional[int]:
    return market.resolution_date.year if market.resolution_date else None


def _facts_conflict(a: Market, b: Market) -> Optional[str]:
    """Return a reason the pair cannot be the same question, or None.

    Numbers are the sharp edge here. "Bitcoin above $100k" and "Bitcoin above
    $120k" are 0.93 similar as strings and are not remotely the same bet.
    """
    facts_a = textlib.title_facts(a.title, _year_of(a))
    facts_b = textlib.title_facts(b.title, _year_of(b))

    # Equality, not overlap. A title stating two thresholds where the other
    # states one is not the same question, and an overlap test would pass it.
    if facts_a.numbers and facts_b.numbers and facts_a.numbers != facts_b.numbers:
        return (
            f"numeric mismatch: {sorted(facts_a.numbers)} vs {sorted(facts_b.numbers)}"
        )
    if facts_a.dates and facts_b.dates and not (facts_a.dates & facts_b.dates):
        return f"date mismatch: {sorted(facts_a.dates)} vs {sorted(facts_b.dates)}"

    # Entities: the subject of the question.
    #
    # Sharing *an* entity is not enough. "Will Italy win the 2030 FIFA World
    # Cup?" and "Will England win the 2030 FIFA World Cup?" share "FIFA",
    # score 0.81 on prose, and are different bets — buying Italy YES against
    # England NO is not a hedge, it is two positions that can both lose.
    #
    # The rule is therefore: reject when each side names a distinctive entity
    # the other does not. A one-sided extra is fine, because venues routinely
    # add context ("BTC above $100k" against "BTC above $100k on Binance");
    # a two-sided difference means the two questions have different subjects.
    entities_a = textlib.entities(textlib.question_part(a.title))
    entities_b = textlib.entities(textlib.question_part(b.title))
    only_a = entities_a - entities_b
    only_b = entities_b - entities_a
    if only_a and only_b:
        return f"conflicting subjects: {sorted(only_a)} vs {sorted(only_b)}"
    return None


def find_pairs(
    markets_a: list[Market],
    markets_b: list[Market],
    threshold: float = 0.72,
    max_candidates_per_market: int = 12,
) -> list[PairCandidate]:
    """Pair equivalent markets across two venues, one-to-one, best first."""
    if not markets_a or not markets_b:
        return []

    index_b = _index_by_token(markets_b)
    scored: list[tuple[float, int, int, list[str]]] = []

    for position_a, market_a in enumerate(markets_a):
        # Candidate generation: markets on B sharing at least one rare token.
        hits: dict[int, int] = defaultdict(int)
        for token in textlib.tokens(market_a.title):
            for position_b in index_b.get(token, ()):
                hits[position_b] += 1
        if not hits:
            continue

        ranked = sorted(hits.items(), key=lambda item: item[1], reverse=True)
        for position_b, _ in ranked[:max_candidates_per_market]:
            market_b = markets_b[position_b]
            score = textlib.similarity(market_a.title, market_b.title)
            if score < threshold:
                continue
            conflict = _facts_conflict(market_a, market_b)
            if conflict:
                continue
            notes = [f"title similarity {score:.3f}"]
            scored.append((score, position_a, position_b, notes))

    # Greedy one-to-one assignment, best score first.
    scored.sort(key=lambda item: item[0], reverse=True)
    used_a: set[int] = set()
    used_b: set[int] = set()
    pairs: list[PairCandidate] = []
    for score, position_a, position_b, notes in scored:
        if position_a in used_a or position_b in used_b:
            continue
        used_a.add(position_a)
        used_b.add(position_b)
        pairs.append(
            PairCandidate(
                market_a=markets_a[position_a],
                market_b=markets_b[position_b],
                score=score,
                notes=notes,
            )
        )
    return pairs


def align_outcomes(pair: PairCandidate) -> PairCandidate:
    """Work out which outcomes are complementary.

    For a binary pair the hedge is YES on one venue against NO on the other,
    in both directions. Which listed outcome *is* the YES side varies: venues
    label them "Yes"/"No", "Mars"/"Not Mars", or by candidate name. The
    reliable signal is the negation convention both venues follow — the NO
    outcome's label is the YES label with a negation prefix.
    """
    a_yes, a_no = _identify_sides(pair.market_a)
    b_yes, b_no = _identify_sides(pair.market_b)
    if not all((a_yes, a_no, b_yes, b_no)):
        pair.complements = []
        return pair

    # Both hedge directions. Each tuple is (buy on A, buy on B) where exactly
    # one of the two pays out.
    pair.complements = [
        (a_yes, b_no),  # YES on A + NO on B
        (a_no, b_yes),  # NO on A + YES on B
    ]
    return pair


_NEGATION_PREFIXES = ("not ", "no ", "won't", "will not", "under", "below", "down")


def _identify_sides(market: Market) -> tuple[Optional[Outcome], Optional[Outcome]]:
    """Return (yes_outcome, no_outcome) for a binary market."""
    if len(market.outcomes) != 2:
        return None, None

    first, second = market.outcomes

    def is_negative(outcome: Outcome) -> bool:
        label = outcome.label.strip().lower()
        return label.startswith(_NEGATION_PREFIXES) or label in {"no", "down"}

    first_negative, second_negative = is_negative(first), is_negative(second)
    if first_negative and not second_negative:
        return second, first
    if second_negative and not first_negative:
        return first, second

    # No negation marker on either label. Every venue observed lists the
    # affirmative outcome first, and the complementary pricing means an
    # inverted guess still produces a valid hedge — it just labels the
    # directions the other way round.
    return first, second
